Repository peauty/peauty-FE, pull requests merged in 2024-11, with the labels that each got.

#3 Feat: Develop 자동 배포 및 typescript 타입 체크 액션 추가
  .github/workflows/deploy.yml
  .github/workflows/type_check.yml
  .yarn/install-state.gz
  .yarnrc.yml
  yarn.lock
Labels: 환경셋팅, 보면 좋아

#1 Feat: 스토리북 추가
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/stories/components/CustomButton/CustomButton.stories.tsx
  src/stories/components/CustomButton/CustomButton.tsx
  src/stories/components/CustomInput/CustomInput.stories.tsx
  src/stories/components/CustomInput/CustomInput.tsx
  src/stories/components/ProgressBar/ProgressBar.stories.tsx
  src/stories/components/ProgressBar/ProgressBar.tsx
  src/stories/components/ProgressBlock/ProgressBlock.stories.tsx
  src/stories/components/ProgressBlock/ProgressBlock.tsx
  src/stories/components/SocialLoginButton/SocialLoginButton.stories.tsx
  src/stories/components/SocialLoginButton/SocialLoginButton.tsx
  src/stories/components/StepProgress/StepProgress.stories.tsx
  src/stories/components/StepProgress/StepProgress.tsx
  src/stories/examples/Button.stories.ts
  src/stories/examples/Button.tsx
  src/stories/examples/Configure.mdx
  src/stories/examples/Header.stories.ts
  src/stories/examples/Header.tsx
  src/stories/examples/Page.stories.ts
  src/stories/examples/Page.tsx
  src/stories/examples/assets/accessibility.png
  src/stories/examples/assets/accessibility.svg
  src/stories/examples/assets/addon-library.png
  src/stories/examples/assets/assets.png
  src/stories/examples/assets/avif-test-image.avif
  src/stories/examples/assets/context.png
  src/stories/examples/assets/discord.svg
  src/stories/examples/assets/docs.png
  src/stories/examples/assets/figma-plugin.png
  src/stories/examples/assets/github.svg
  src/stories/examples/assets/share.png
  src/stories/examples/assets/styling.png
  src/stories/examples/assets/testing.png
  src/stories/examples/assets/theming.png
  src/stories/examples/assets/tutorials.svg
  src/stories/examples/assets/youtube.svg
  src/stories/examples/button.css
  src/stories/examples/header.css
  src/stories/examples/page.css
  yarn.lock
Labels: 한명 이상 봐줘, 새로운 기능, 환경셋팅

#5 [PEAUTY-31] 글로벌 스타일 추가 적용
  index.html
  src/assets/fonts/Pretendard-Medium.subset.woff
  src/assets/fonts/Pretendard-Regular.subset.woff
  src/assets/fonts/Pretendard-SemiBold.subset.woff
  src/global-style.ts
  src/main.tsx
  src/page/main/index.styles.ts
  src/page/main/index.tsx
  src/page/my-page/index.styles.ts
  src/page/my-page/index.tsx
  src/style/color.ts
  src/style/fonts.css
  src/style/global-style.ts
  src/style/normalize.css
  src/style/theme.ts
  src/style/typography.ts
  yarn.lock
Labels: 환경셋팅, 보면 좋아

#11 feat: 버튼 색상 변경
  src/components/global/CustomButton/CustomButton.tsx
Labels: 환경셋팅

#9 [PEAUTY-44] 선택 후 이동이 가능한 컴포넌트 생성
  public/svg/Arrow.svg
  src/assets/svg/Arrow.tsx
  src/assets/svg/index.ts
  src/components/global/SubMenu/SubMenu.stories.tsx
  src/components/global/SubMenu/SubMenu.tsx
Labels: 환경셋팅

#7 [PEAUTY-36] Input에 Button 추가 컴포넌트 생성
  src/components/global/CustomButton/CustomButton.tsx
  src/components/global/CustomInput/CustomInput.stories.tsx
  src/components/global/CustomInput/CustomInput.tsx
Labels: 환경셋팅

#8 [PEAUTY-42] 태그 컴포넌트 생성
  src/components/global/Tag/Tag.stories.tsx
  src/components/global/Tag/Tag.tsx
Labels: 환경셋팅

#12 [PEAUTY-37] 큰 버튼 컴포넌트 생성
  src/components/global/SelectButton/SelectButton.stories.ts
  src/components/global/SelectButton/SelectButton.tsx
Labels: 환경셋팅

#10 Docs: update readme
  README.md
Labels: 두명 이상 봐줘

#14 Refactor: 컴포넌트 세분화 및 생성 스크립트 생성
  create_global_component.js
  src/components/global/AppBar/AppBar.stories.tsx
  src/components/global/AppBar/AppBar.styles.ts
  src/components/global/AppBar/AppBar.tsx
  src/components/global/AppBar/index.ts
  src/components/global/CustomButton/CustomButton.stories.tsx
  src/components/global/CustomButton/CustomButton.styles.ts
  src/components/global/CustomButton/CustomButton.tsx
  src/components/global/CustomButton/index.ts
  src/components/global/CustomInput/CustomButton.styles.ts
  src/components/global/CustomInput/CustomInput.stories.tsx
  src/components/global/CustomInput/CustomInput.tsx
  src/components/global/CustomInput/index.ts
  src/components/global/ProgressBar/ProgressBar.stories.tsx
  src/components/global/ProgressBar/ProgressBar.styles.ts
  src/components/global/ProgressBar/ProgressBar.tsx
  src/components/global/ProgressBar/index.ts
  src/components/global/ProgressBlock/ProgressBlock.stories.tsx
  src/components/global/ProgressBlock/ProgressBlock.styles.ts
  src/components/global/ProgressBlock/ProgressBlock.tsx
  src/components/global/ProgressBlock/index.ts
  src/components/global/SelectButton/SelectButton.stories.ts
  src/components/global/SelectButton/SelectButton.styles.ts
  src/components/global/SelectButton/SelectButton.tsx
  src/components/global/SelectButton/index.ts
  src/components/global/SocialLoginButton/SocialLoginButton.styles.ts
  src/components/global/SocialLoginButton/SocialLoginButton.tsx
  src/components/global/SocialLoginButton/index.ts
  src/components/global/StepProgress/StepProgress.stories.tsx
  src/components/global/StepProgress/StepProgress.styles.ts
  src/components/global/StepProgress/StepProgress.tsx
  src/components/global/StepProgress/index.ts
  src/components/global/SubMenu/SubMenu.stories.tsx
  src/components/global/SubMenu/SubMenu.styles.ts
  src/components/global/SubMenu/SubMenu.tsx
  src/components/global/SubMenu/index.ts
  src/components/global/Tag/Tag.stories.tsx
  src/components/global/Tag/Tag.styles.ts
  src/components/global/Tag/Tag.tsx
  src/components/global/Tag/index.ts
Labels: 모두가 봐야해, 새로운 기능, 환경셋팅

#13 [PEAUTY-38] 버튼 그리드 생성
  src/components/global/ButtonGrid/ButtonGrid.stories.tsx
  src/components/global/ButtonGrid/ButtonGrid.styles.ts
  src/components/global/ButtonGrid/ButtonGrid.tsx
  src/components/global/ButtonGrid/index.ts
Labels: 환경셋팅

#15 [PEAUTY-43] GNB 생성
  public/svg/bookmark.svg
  public/svg/calendar.svg
  public/svg/home.svg
  public/svg/search.svg
  public/svg/smile.svg
  src/assets/svg/Bookmark.tsx
  src/assets/svg/Calendar.tsx
  src/assets/svg/Home.tsx
  src/assets/svg/Search.tsx
  src/assets/svg/Smile.tsx
  src/assets/svg/index.ts
  src/components/global/GNB/GNB.stories.tsx
  src/components/global/GNB/GNB.styles.ts
  src/components/global/GNB/GNB.tsx
  src/components/global/GNB/index.ts
Labels: 한명 이상 봐줘, 환경셋팅

#18 [PEAUTY-60] Layout 컴포넌트 생성 및 경로 index. ts 추가
  src/components/global/layout/Layout/Layout.styles.ts
  src/components/global/layout/Layout/Layout.tsx
  src/components/global/layout/Layout/index.ts
  src/components/index.ts
Labels: 모두가 봐야해, 보면 좋아

#21 router 설정 변경
  src/App.tsx
  src/main.tsx
  src/pages/my-page/pet/edit/index.styles.ts
  src/pages/my-page/pet/edit/index.tsx
  src/pages/not-found/index.styles.ts
  src/pages/not-found/index.tsx
  src/router.tsx
Labels: 모두가 봐야해

#20 [PEAUTY-62] 토스트 컴포넌트 생성
  public/svg/check.svg
  src/assets/svg/Check.tsx
  src/assets/svg/index.ts
  src/components/global/toast/Toast.stories.tsx
  src/components/global/toast/Toast.styles.ts
  src/components/global/toast/Toast.tsx
  src/components/global/toast/index.ts
Labels: 새로운 기능, 환경셋팅

#22 65 브랜치 업데이트
  src/components/global/button/MultiSelectButton/MultiSelectButton.stories.tsx
  src/components/global/button/MultiSelectButton/MultiSelectButton.tsx
  src/components/global/button/SelectButton/SelectButton.tsx
  src/components/global/category/Tag/Tag.tsx
  src/components/global/input/CustomInput/CustomInput.styles.ts
  src/components/global/input/CustomInput/CustomInput.tsx
  src/components/global/texts/Text/Text.stories.ts
  src/components/global/texts/Text/Text.styles.ts
  src/components/global/texts/Text/Text.tsx
  src/components/global/toast/Toast.tsx
  src/pages/my-page/pet/edit/index.styles.ts
  src/pages/my-page/pet/edit/index.tsx
Labels: 모두가 봐야해

#27 [PEAUTY-64] 드롭다운 버튼 생성
  .github/workflows/type_check.yml
  public/svg/DropDown.svg
  src/assets/svg/DropDown.tsx
  src/assets/svg/index.ts
  src/components/global/button/DropButton/DropButton.stories.tsx
  src/components/global/button/DropButton/DropButton.styles.ts
  src/components/global/button/DropButton/DropButton.tsx
  src/components/global/button/DropButton/index.ts
  src/components/index.ts
Labels: 보면 좋아

#26 [PEAUTY-58] GNB 수정 및 Layout 변경
  src/components/global/layout/AppBar/AppBar.styles.ts
  src/components/global/layout/GNB/GNB.stories.tsx
  src/components/global/layout/GNB/GNB.styles.ts
  src/components/global/layout/GNB/GNB.tsx
  src/components/global/layout/Layout/Layout.styles.ts
  src/components/global/layout/Layout/Layout.tsx
  src/components/global/texts/Text/Text.stories.ts
  src/pages/main/index.tsx
  src/router.tsx
  src/style/global-style.ts
  src/style/theme.ts
Labels: 보면 좋아

#28 [PEAUTY-73] Wrapper 컴포넌트 생성 및 AppBar 수정
  README.md
  public/svg/Maker.svg
  src/assets/svg/Logo.tsx
  src/assets/svg/Maker.tsx
  src/assets/svg/index.ts
  src/components/global/layout/AppBar/AppBar.stories.tsx
  src/components/global/layout/AppBar/AppBar.styles.ts
  src/components/global/layout/AppBar/AppBar.tsx
  src/components/global/layout/Layout/Layout.styles.ts
  src/components/global/layout/Layout/index.ts
  src/components/global/layout/Wrpper/Wrapper.styles.ts
  src/components/global/layout/Wrpper/Wrapper.tsx
  src/components/global/layout/Wrpper/index.ts
  src/components/index.ts
  src/components/page/main/EstimateStatus.tsx
  src/pages/main/index.tsx
  src/router.tsx
  src/style/typography.ts
Labels: 보면 좋아

#29 [PEAUTY-77] 뱃지 및 스타일리스트아이템 컴포넌트 생성
  public/svg/Auth.svg
  public/svg/ScissorsIcon.svg
  public/svg/Star.svg
  src/assets/svg/Auth.tsx
  src/assets/svg/Home.tsx
  src/assets/svg/ScissorsIcon.tsx
  src/assets/svg/Star.tsx
  src/assets/svg/index.ts
  src/components/global/category/Badge/Badge.stories.tsx
  src/components/global/category/Badge/Badge.styles.ts
  src/components/global/category/Badge/Badge.tsx
  src/components/global/category/Badge/index.ts
  src/components/global/category/Tag/Tag.stories.tsx
  src/components/global/layout/Layout/Layout.styles.ts
  src/components/global/layout/Wrpper/Wrapper.styles.ts
  src/components/global/stylist-Item/StylistItem.stories.tsx
  src/components/global/stylist-Item/StylistItem.styles.ts
  src/components/global/stylist-Item/StylistItem.tsx
  src/pages/main/index.tsx
  src/style/color.ts
  src/style/typography.ts
  tsconfig.json
Labels: 새로운 기능, 환경셋팅

#32 Feat: Intro, SignIn, SignUp, SignUpComplete 페이지 생성
  .yarn/install-state.gz
  package.json
  public/svg/warning.svg
  src/apis/api.ts
  src/apis/resources/external/kakaoMapAPI.ts
  src/apis/resources/user/index.ts
  src/assets/images/symbol.png
  src/assets/svg/Logo.tsx
  src/assets/svg/Warning.tsx
  src/assets/svg/index.ts
  src/components/index.ts
  src/components/page/sign-in/SocialLoginButton/SocialLoginButton.tsx
  src/components/page/sign-in/SocialLoginModal/SocialLoginModal.styles.ts
  src/components/page/sign-in/SocialLoginModal/SocialLoginModal.tsx
  src/components/page/sign-in/SocialLoginModal/index.ts
  src/hooks/useLocation.ts
  src/hooks/useUser.ts
  src/main.tsx
  src/pages/intro/index.styles.ts
  src/pages/intro/index.tsx
  src/pages/main/index.styles.ts
  src/pages/my-page/index.styles.ts
  src/pages/my-page/index.tsx
  src/pages/sign-in/index.styles.ts
  src/pages/sign-in/index.styles.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-up-complete/index.styles.ts
  src/pages/sign-up-complete/index.tsx
  src/pages/sign-up/StepWords.ts
  src/pages/sign-up/index.styles.ts
  src/pages/sign-up/index.tsx
  src/router.tsx
  src/types/user/index.ts
  tsconfig.json
  yarn.lock
Labels: 두명 이상 봐줘, 새로운 기능
