Repository peauty/peauty-FE, pull requests merged in 2024-12, with the labels that each got.

#35 Feat: InfoButton 생성
  src/components/button/InfoButton/InfoButton.stories.tsx
  src/components/button/InfoButton/InfoButton.styles.ts
  src/components/button/InfoButton/InfoButton.tsx
  src/components/button/InfoButton/index.ts
Labels: 보면 좋아

#37 Feat: API 및 Type 생성 스크립트 생성
  generate-apis-and-types.js
  generate-global-component.js
  src/apis/api.ts
  src/apis/resources/auth/index.ts
  src/apis/resources/customer/index.ts
  src/apis/resources/internal/index.ts
  src/apis/resources/puppy/index.ts
  src/apis/resources/user/index.ts
  src/hooks/useUser.ts
  src/pages/sign-up/index.tsx
  src/types/auth/index.ts
  src/types/customer/index.ts
  src/types/internal/index.ts
  src/types/puppy/index.ts
  src/types/user/index.ts
Labels: 새로운 기능, 환경셋팅, 보면 좋아

#34 feat: 카드 컴포넌트 생성 및 태그 컴포넌트 수정
  src/components/cards/Card/Card.stories.tsx
  src/components/cards/Card/Card.styles.ts
  src/components/cards/Card/Card.tsx
  src/components/cards/Card/index.ts
  src/components/category/Tag/Tag.stories.tsx
  src/components/category/Tag/Tag.styles.ts
  src/components/category/Tag/Tag.tsx
  src/components/texts/Text/Text.styles.ts
Labels: 한명 이상 봐줘

#36 Feat: 마이페이지
  src/components/category/Tag/Tag.styles.ts
  src/pages/my-page/index.styles.ts
  src/pages/my-page/index.tsx
  src/router.tsx
Labels: 한명 이상 봐줘

#41 [PEAUTY-94] useUserdetail 훅 추가
  src/hooks/useUserDetails.ts
Labels: 두명 이상 봐줘

#43 fix: 라우팅 경로 대대적인 수정
  src/constants/routes.ts
  src/main.tsx
  src/pages/customer/mypage/index.styles.ts
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/edit/components/DatePicker.tsx
  src/pages/customer/pet/edit/index.styles.ts
  src/pages/customer/pet/edit/index.tsx
  src/pages/customer/sign-up-complete/index.styles.ts
  src/pages/customer/sign-up-complete/index.tsx
  src/pages/customer/sign-up/StepWords.ts
  src/pages/customer/sign-up/index.styles.ts
  src/pages/customer/sign-up/index.tsx
  src/pages/designer/mypage/index.styles.ts
  src/pages/designer/mypage/index.tsx
  src/pages/designer/signup-complete/index.styles.ts
  src/pages/designer/signup-complete/index.tsx
  src/pages/designer/signup-detail-complete/index.styles.ts
  src/pages/designer/signup-detail-complete/index.tsx
  src/pages/designer/signup-detail/index.styles.ts
  src/pages/designer/signup-detail/index.tsx
  src/pages/designer/signup/index.styles.ts
  src/pages/designer/signup/index.tsx
  src/router.tsx
  src/router/customer/index.tsx
  src/router/customer/pet/index.tsx
  src/router/designer/index.tsx
  src/router/root/index.tsx
  src/router/router.tsx
Labels: 모두가 봐야해, 환경셋팅

#47 Fix: Chromatic 테스트 겸 Button width 수정
  .github/workflows/storybook.yml
  package.json
  src/components/button/CustomButton/CustomButton.styles.ts
  yarn.lock
Labels: 한명 이상 봐줘, 새로운 기능, 환경셋팅

#55 Feat: 마이페이지 내정보 수정 페이지
  src/constants/routes.ts
  src/pages/customer/mypage-edit/CustomerMyPageEdit.styles.ts
  src/pages/customer/mypage-edit/CustomerMyPageEdit.tsx
  src/pages/customer/mypage-edit/index.ts
  src/router/customer/index.tsx
  yarn.lock
Labels: 보면 좋아

#56 Feat: API 요청시 JWT 토큰을 담아서 보내기
  src/apis/api.ts
  src/constants/routes.ts
  src/hooks/useUser.ts
  src/hooks/useUserDetails.ts
  src/pages/main/index.tsx
  src/pages/sign-in/index.tsx
  src/router/customer/index.tsx
  src/router/root/index.tsx
Labels: 환경셋팅, 보면 좋아

#57 fix: 회원가입 로딩 추가 및 잔잔바리 수정
  src/apis/api.ts
  src/components/layout/GNB/GNB.tsx
  src/components/page/sign-up/Loading/index.tsx
  src/hooks/useUser.ts
  src/pages/customer/sign-up-complete/index.tsx
  src/pages/customer/sign-up/index.styles.ts
  src/pages/customer/sign-up/index.tsx
Labels: 보면 좋아

#64 refactor: API 및 Type 경로 변경
  generate-apis-and-types.js
  src/apis/customer/api.ts
  src/apis/customer/resources/auth/index.ts
  src/apis/customer/resources/customer/index.ts
  src/apis/customer/resources/internal/index.ts
  src/apis/customer/resources/puppy/index.ts
  src/apis/designer/api.ts
  src/apis/designer/resources/auth/index.ts
  src/apis/designer/resources/designer/index.ts
  src/apis/designer/resources/internal/index.ts
  src/apis/external/kakaoMapAPI.ts
  src/hooks/useLocation.ts
  src/hooks/useUser.ts
  src/pages/customer/sign-up/index.tsx
  src/types/customer/auth/index.ts
  src/types/customer/customer/index.ts
  src/types/customer/internal/index.ts
  src/types/customer/puppy/index.ts
  src/types/designer/auth/index.ts
  src/types/designer/designer/index.ts
  src/types/designer/internal/index.ts
Labels: 환경셋팅

#66 💄 Fix: Card 및 Tag 컴포넌트 텍스트만 받도록 수정
  src/components/cards/Card/Card.stories.tsx
  src/components/cards/Card/Card.tsx
  src/components/category/Tag/Tag.stories.tsx
  src/components/category/Tag/Tag.styles.ts
  src/components/category/Tag/Tag.tsx
  src/pages/customer/mypage/index.tsx
Labels: 보면 좋아

#58 [PEAUTY-115] 디자이너 관점 뱃지 및 마이 페이지 UI구현
  public/svg/Firework.svg
  public/svg/Medal.svg
  src/assets/svg/Firework.tsx
  src/assets/svg/Medal.tsx
  src/assets/svg/index.ts
  src/pages/designer/mypage/badges/components/Badges/Badges.styles.ts
  src/pages/designer/mypage/badges/components/Badges/Badges.tsx
  src/pages/designer/mypage/badges/index.styles.ts
  src/pages/designer/mypage/badges/index.tsx
  src/pages/designer/mypage/index.styles.ts
  src/pages/designer/mypage/index.tsx
  src/router/designer/index.tsx
Labels: 두명 이상 봐줘, 보면 좋아

#69 [PEAUTY-151] input 컴포넌트에서 input과 textarea 둘 다 선택적으로 사용할 수 있도록 type 추가
  src/components/input/CustomInput/CustomInput.styles.ts
  src/components/input/CustomInput/CustomInput.tsx
  src/pages/designer/signup-detail/index.tsx
Labels: 모두가 봐야해

#70 [PEAUTY-157] input 컴포넌트와 textarea 컴포넌트 사이 높이 조정
  src/components/button/LocationButton/LocationButton.styles.ts
  src/components/button/LocationButton/LocationButton.tsx
  src/pages/designer/signup-detail/index.styles.ts
  src/pages/designer/signup-detail/index.tsx
Labels: 보면 좋아

#68 [PEAUTY-136] 디자이너 수정 페이지 UI
  src/apis/customer/resources/internal/index.ts
  src/components/input/CustomInput/CustomInput.styles.ts
  src/pages/designer/mypage/edit/index.styles.ts
  src/pages/designer/mypage/edit/index.tsx
  src/router/designer/index.tsx
  src/types/customer/auth/index.ts
  src/types/customer/internal/index.ts
Labels: 한명 이상 봐줘

#76 [PEAUTY-159] 홈 경로를 Intro로 변경
  src/pages/intro/index.tsx
  src/router/root/index.tsx
Labels: 모두가 봐야해

#75 [PEAUTY-59] 고객관점 메인페이지 UI 생성
  src/assets/images/배너.png
  src/components/carousel/Carousel.styles.ts
  src/components/category/Badge/Badge.styles.ts
  src/components/index.ts
  src/components/layout/GNB/GNB.tsx
  src/components/layout/Wrpper/Wrapper.styles.ts
  src/components/stylist-Item/StylistItem.stories.tsx
  src/components/stylist-Item/StylistItem.styles.ts
  src/components/stylist-Item/StylistItem.tsx
  src/constants/routes.ts
  src/pages/main/components/AD/index.styles.ts
  src/pages/main/components/AD/index.tsx
  src/pages/main/components/EstimateStatus.tsx
  src/pages/main/components/NewStore/index.styles.ts
  src/pages/main/components/NewStore/index.tsx
  src/pages/main/components/PopularStore/index.styles.ts
  src/pages/main/components/PopularStore/index.tsx
  src/pages/main/components/ProposalItem/index.styles.ts
  src/pages/main/components/ProposalItem/index.tsx
  src/pages/main/components/ProposalStatusNav/index.stlyes.ts
  src/pages/main/components/ProposalStatusNav/index.tsx
  src/pages/main/index.styles.ts
  src/pages/main/index.tsx
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/router/router.tsx
  src/style/typography.ts
Labels: 새로운 기능

#77 [PEAUTY-145] 미용사 회원가입
  src/components/layout/GNB/GNB.tsx
  src/constants/routes.ts
  src/pages/customer/sign-up-complete/index.tsx
  src/pages/designer/home/index.tsx
  src/pages/designer/signup-complete/index.styles.ts
  src/pages/designer/signup-complete/index.tsx
  src/pages/designer/signup/index.styles.ts
  src/pages/designer/signup/index.tsx
  src/pages/designer/signup/stepWords.ts
  src/pages/sign-in/components/SocialLoginModal/SocialLoginModal.tsx
  src/pages/sign-in/index.tsx
  src/router/designer/index.tsx
Labels: 보면 좋아

#80 fix: 로그인 과정 수정 및 전역 타입 설정
  src/hooks/useUserDetails.ts
  src/pages/sign-in/index.tsx
  src/types/ types.d.ts
Labels: 환경셋팅, 보면 좋아

#73 [PEAUTY-138] 미용사 리스트 (요청하기) UI
  public/svg/SelectIcon.svg
  src/apis/customer/resources/customer/index.ts
  src/apis/customer/resources/internal/index.ts
  src/apis/customer/resources/puppy/index.ts
  src/apis/designer/resources/auth/index.ts
  src/apis/designer/resources/designer/index.ts
  src/apis/designer/resources/internal/index.ts
  src/assets/svg/SelectIcon.tsx
  src/assets/svg/index.ts
  src/components/category/Badge/Badge.styles.ts
  src/components/rating/Rating.tsx
  src/components/stylist-Item/StylistItem.styles.ts
  src/components/stylist-Item/StylistItem.tsx
  src/pages/customer/sign-up/index.tsx
  src/pages/request/components/DesignerListItem/index.styles.ts
  src/pages/request/components/DesignerListItem/index.tsx
  src/pages/request/index.styles.ts
  src/pages/request/index.tsx
  src/router/router.tsx
  src/types/customer/auth/index.ts
  src/types/customer/customer/index.ts
  src/types/customer/internal/index.ts
  src/types/customer/puppy/index.ts
  src/types/designer/designer bidding api/index.ts
  src/types/designer/designer/index.ts
Labels: 새로운 기능

#79 [PEAUTY-168] 요청하기, 미용사 가게 리스트 api 연결
  src/apis/customer/resources/auth/index.ts
  src/components/layout/GNB/GNB.tsx
  src/components/rating/Rating.stories.tsx
  src/components/rating/Rating.tsx
  src/constants/routes.ts
  src/hooks/useUserDetails.ts
  src/pages/main/index.tsx
  src/pages/request/components/DesignerListItem/index.styles.ts
  src/pages/request/components/DesignerListItem/index.tsx
  src/pages/request/index.styles.ts
  src/pages/request/index.tsx
  src/pages/shop/components/ShopReview/ReviewItem/index.tsx
  src/pages/shop/components/ShopReview/index.tsx
  src/pages/sign-in/index.tsx
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/router/router.tsx
  src/types/customer/customer/index.ts
  src/types/customer/request/index.tsx
  src/types/designer/designer bidding api/index.ts
  src/types/designer/designer/index.ts
Labels: 두명 이상 봐줘, 새로운 기능

#78 [PEAUTY-171] 디자이너 마이페이지 api 연동
  src/apis/designer/resources/designer/index.ts
  src/pages/designer/mypage/badges/index.tsx
  src/pages/designer/mypage/detail/index.tsx
  src/pages/designer/mypage/edit/index.styles.ts
  src/pages/designer/mypage/edit/index.tsx
  src/pages/designer/mypage/index.tsx
  src/types/designer/designer/index.ts
Labels: 보면 좋아

#83 [PEAUTY-164] 견적서 작성 UI 생성
  src/components/cards/Card/Card.styles.ts
  src/components/index.ts
  src/components/input/CustomInput/CustomInput.styles.ts
  src/pages/designer/quote/index.styles.ts
  src/pages/designer/quote/index.tsx
  src/router/customer/index.tsx
  src/router/designer/index.tsx
  src/router/router.tsx
  src/style/color.ts
  src/style/typography.ts
Labels: 새로운 기능

#84 fix: 라우터 변경
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/router/designer/home/index.tsx
  src/router/designer/index.tsx
  src/router/designer/mypage/index.tsx
  src/router/designer/quote/index.tsx
  src/router/designer/signup/index.tsx
  src/style/layoutStyle.ts
Labels: 환경셋팅

#72 [PEAUTY-157] /designer/signup-detail 페이지 컴포넌트 분리 및 API 연결
  package.json
  src/components/button/LocationButton/LocationButton.styles.ts
  src/components/button/LocationButton/LocationButton.tsx
  src/components/button/MultiSelectButton/MultiSelectButton.stories.tsx
  src/components/button/MultiSelectButton/MultiSelectButton.tsx
  src/components/button/RadioSelectButton/RadioSelectButton.stories.tsx
  src/components/input/CustomInput/CustomInput.styles.ts
  src/components/input/CustomInput/CustomInput.tsx
  src/components/input/TitleContentInput/TitleContentInput.stories.tsx
  src/components/input/TitleContentInput/TitleContentInput.styles.ts
  src/components/input/TitleContentInput/TitleContentInput.tsx
  src/components/input/TitleContentInput/index.ts
  src/pages/customer/pet/edit/index.tsx
  src/pages/designer/signup-detail/components/CertificateInputSection.tsx
  src/pages/designer/signup-detail/components/CoverPhotoUploadSection.tsx
  src/pages/designer/signup-detail/components/SearchLocationModal.tsx
  src/pages/designer/signup-detail/components/ShopInfoInputSection.tsx
  src/pages/designer/signup-detail/index.styles.ts
  src/pages/designer/signup-detail/index.tsx
  yarn.lock
Labels: 모두가 봐야해

#85 AppBar의 backButton에 기본 동작(뒤로가기) 넣기
  src/components/layout/AppBar/AppBar.tsx
  src/pages/customer/mypage/detail/index.tsx
  src/pages/customer/pet/edit/index.tsx
Labels: 보면 좋아

#87 [PEAUTY-201] DateDrop Box 컴포넌트 생성
  src/components/button/DateDropBox/DateDropBox.styles.ts
  src/components/button/DateDropBox/DateDropBox.tsx
Labels: 새로운 기능

#88 [PEAUTY-178] 영문화된 svg와 스타일 연결
  src/pages/customer/request/customize-grooming/index.tsx
Labels: 버그픽스

#86 [PEAUTY-192]: 디자이너 추가정보 이미지 업로드 API 연동
  src/assets/svg/AddImage.tsx
  src/pages/designer/signup-detail/components/CoverPhotoUploadSection.tsx
  src/pages/designer/signup-detail/index.styles.ts
Labels: 보면 좋아

#91 [PEAUTY-174] 리뷰 작성 페이지 UI
  public/svg/HeartTag.svg
  public/svg/MoneyTag.svg
  public/svg/PinTag.svg
  public/svg/QuoteTag.svg
  public/svg/StarBlue.svg
  public/svg/StarGray.svg
  public/svg/TeddyTag.svg
  src/assets/svg/HeartTag.tsx
  src/assets/svg/MoneyTag.tsx
  src/assets/svg/PinTag.tsx
  src/assets/svg/QuoteTag.tsx
  src/assets/svg/StarBlue.tsx
  src/assets/svg/StarGray.tsx
  src/assets/svg/TeddyTag.tsx
  src/assets/svg/index.ts
  src/components/input/CustomInput/CustomInput.tsx
  src/pages/customer/review/write-review/components/ReviewableService.tsx
  src/pages/customer/review/write-review/components/TagList.tsx
  src/pages/customer/review/write-review/index.styles.ts
  src/pages/customer/review/write-review/index.tsx
  src/router/customer/mypage/index.tsx
Labels: 보면 좋아

#74 [PEAUTY-40] 강아지 등록 페이지
  public/svg/PetProfile.svg
  src/apis/customer/hooks/signUpCustomHook.tsx
  src/assets/svg/PetProfile.tsx
  src/pages/customer/pet/signup/components/Step/step1.tsx
  src/pages/customer/pet/signup/components/Step/step2.tsx
  src/pages/customer/pet/signup/components/Step/step3.tsx
  src/pages/customer/pet/signup/index.styles.ts
  src/pages/customer/pet/signup/index.tsx
  src/router/customer/pet/index.tsx
  src/types/customer/puppy/index.ts
Labels: 두명 이상 봐줘

#90 [PEAUTY-175] 견적서 보기 UI 생성
  public/svg/CheckIcon2.svg
  src/assets/svg/CheckIcon2.tsx
  src/assets/svg/index.ts
  src/pages/customer/quote-detail/index.styles.ts
  src/pages/customer/quote-detail/index.tsx
  src/router/customer/index.tsx
Labels: 보면 좋아

#92 [PEAUTY-189] 고객 및 미용사 입찰 시스템 페이지 ui
  src/components/petInfo/Info.styles.ts
  src/components/petInfo/Info.tsx
  src/components/profile-img/ProfileImg/ProfileImg.styles.ts
  src/components/profile-img/ProfileImg/ProfileImg.tsx
  src/pages/customer/status/components/CustomerInfo/index.styles.ts
  src/pages/customer/status/components/CustomerInfo/index.tsx
  src/pages/customer/status/components/DogProfile/index.styles.ts
  src/pages/customer/status/components/DogProfile/index.tsx
  src/pages/customer/status/components/Info/ index.styles.ts
  src/pages/customer/status/components/Info/index.tsx
  src/pages/customer/status/components/StatusListItem/index.styles.ts
  src/pages/customer/status/components/StatusListItem/index.tsx
  src/pages/customer/status/components/StatusTab/index.styles.ts
  src/pages/customer/status/components/StatusTab/index.tsx
  src/pages/customer/status/index.styles.ts
  src/pages/customer/status/index.tsx
  src/pages/designer/status/components/RequsetTab/index.styles.ts
  src/pages/designer/status/components/RequsetTab/index.tsx
  src/pages/designer/status/index.styles.ts
  src/pages/designer/status/index.tsx
  src/router/customer/index.tsx
  src/router/customer/status/index.tsx
  src/router/designer/index.tsx
  src/router/designer/status/index.tsx
Labels: 한명 이상 봐줘

#93 [PEAUTY-193] 강아지 조회
  src/components/cards/Card/Card.styles.ts
  src/components/cards/Card/Card.tsx
  src/constants/routes.ts
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/info/index.tsx
  src/router/customer/pet/index.tsx
Labels: 보면 좋아

#97 [PEAUTY-212] 강아지 CRUD
  public/svg/Male.svg
  src/apis/customer/hooks/signUpCustomHook.tsx
  src/apis/customer/resources/auth/index.ts
  src/assets/svg/Male.tsx
  src/assets/svg/index.ts
  src/components/button/DropButton/DropButton.tsx
  src/components/button/MultiSelectButton/MultiSelectButton.tsx
  src/components/cards/Card/Card.styles.ts
  src/components/cards/Card/Card.tsx
  src/components/input/TitleContentInput/TitleContentInput.stories.tsx
  src/constants/puppy.ts
  src/constants/routes.ts
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/edit/components/DatePicker.tsx
  src/pages/customer/pet/edit/index.tsx
  src/pages/customer/pet/info/components/Gender.tsx
  src/pages/customer/pet/info/components/Modal.styles.ts
  src/pages/customer/pet/info/components/Modal.tsx
  src/pages/customer/pet/info/index.styles.ts
  src/pages/customer/pet/info/index.tsx
  src/router/customer/pet/index.tsx
  src/types/customer/puppy/index.ts
Labels: 보면 좋아

#96 [PEAUTY-174] 리뷰 페이지
  public/svg/pen.svg
  src/assets/svg/Pen.tsx
  src/assets/svg/index.ts
  src/constants/routes.ts
  src/pages/customer/review/history/components/ReviewTabs.tsx
  src/pages/customer/review/history/components/ReviewableService.tsx
  src/pages/customer/review/history/components/ReviewedService.tsx
  src/pages/customer/review/history/index.styles.ts
  src/pages/customer/review/history/index.tsx
  src/pages/customer/review/write-review/components/Star/StarChanger.tsx
  src/pages/customer/review/write-review/components/Star/StarItem.tsx
  src/pages/customer/review/write-review/components/TagList.tsx
  src/pages/customer/review/write-review/index.styles.ts
  src/pages/customer/review/write-review/index.tsx
  src/pages/customer/status/components/CustomerInfo/index.styles.ts
  src/pages/customer/status/components/CustomerInfo/index.tsx
  src/router/customer/mypage/index.tsx
Labels: 한명 이상 봐줘

#100 [PEAUTY-221] 결제 완료 UI 구현
  public/svg/Circle.svg
  public/svg/payment.svg
  src/assets/svg/Circle.tsx
  src/assets/svg/Payment.tsx
  src/assets/svg/index.ts
  src/pages/customer/payment/index.styles.ts
  src/pages/customer/payment/index.tsx
  src/router/customer/index.tsx
  src/router/customer/payment/index.tsx
Labels: 한명 이상 봐줘

#102 [PEAUTY-227] 고객 관점 내요청보기 페이지
  src/components/button/DropButton/DropButton.tsx
  src/components/button/RadioSelectButton/RadioSelectButton.tsx
  src/pages/customer/request/request-look/index.styles.ts
  src/pages/customer/request/request-look/index.tsx
  src/router/customer/request/index.tsx
Labels: 한명 이상 봐줘

#103 [feature/PEAUTY-232] 미용사 스케줄 페이지 생성 UI
  src/components/stylist-Item/StylistItem.tsx
  src/pages/designer/schedule/components/Dashboard.tsx
  src/pages/designer/schedule/index.styles.ts
  src/pages/designer/schedule/index.tsx
  src/router/designer/index.tsx
  src/router/designer/quote/index.tsx
  src/router/designer/status/index.tsx
Labels: 새로운 기능, 보면 좋아

#104 [PEAUTY-174] 요청함 디테일 수정
  public/svg/clock.svg
  src/assets/svg/Clock.tsx
  src/assets/svg/index.ts
  src/components/petInfo/Info.styles.ts
  src/components/petInfo/Info.tsx
  src/components/rating/Rating.styles.ts
  src/components/rating/Rating.tsx
  src/pages/customer/review/history/components/ReviewableService.tsx
  src/pages/customer/status/components/CustomerInfo/index.styles.ts
  src/pages/customer/status/components/CustomerInfo/index.tsx
  src/pages/customer/status/components/DogProfile/index.styles.ts
  src/pages/customer/status/components/Info/index.styles.ts
  src/pages/customer/status/components/Info/index.tsx
  src/pages/customer/status/components/StatusListItem/index.styles.ts
  src/pages/customer/status/components/StatusTab/index.styles.ts
  src/pages/customer/status/components/StatusTab/index.tsx
  src/pages/customer/status/index.styles.ts
  src/pages/customer/status/index.tsx
  src/pages/designer/status/components/StatusTab/index.styles.ts
  src/pages/designer/status/components/StatusTab/index.tsx
  src/pages/designer/status/index.styles.ts
  src/pages/designer/status/index.tsx
Labels: 보면 좋아

#105 ## [PEAUTY-225] 견적 요청하기 API 연동
  generate-apis-and-types.js
  src/apis/customer/hooks/signUpCustomHook.tsx
  src/apis/customer/resources/customer-bidding-api/index.ts
  src/components/button/DateDropBox/DateDropBox.tsx
  src/components/layout/GNB/GNB.tsx
  src/constants/routes.ts
  src/pages/customer/request/choose-pet/index.tsx
  src/pages/customer/request/components/choose-pet/index.styles.ts
  src/pages/customer/request/components/choose-pet/index.tsx
  src/pages/customer/request/components/customize-grooming/components/DropBox/index.styles.ts
  src/pages/customer/request/components/customize-grooming/components/DropBox/index.tsx
  src/pages/customer/request/components/customize-grooming/index.styles.ts
  src/pages/customer/request/components/customize-grooming/index.tsx
  src/pages/customer/request/components/notice/index.styles.ts
  src/pages/customer/request/components/notice/index.tsx
  src/pages/customer/request/components/search/components/DesignerListItem/index.styles.ts
  src/pages/customer/request/components/search/components/DesignerListItem/index.tsx
  src/pages/customer/request/components/search/index.styles.ts
  src/pages/customer/request/components/search/index.tsx
  src/pages/customer/request/customize-grooming/index.styles.ts
  src/pages/customer/request/customize-grooming/index.tsx
  src/pages/customer/request/hooks/useEstimateProposalForm.tsx
  src/pages/customer/request/index.tsx
  src/pages/request/index.tsx
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/types/customer/customer-bidding-api/index.ts
  src/types/customer/customer/index.ts
Labels: 보면 좋아

#106 [PEAUTY-179] Shop 상세 연결 및 수정
  src/apis/resources/designer/index.ts
  src/components/carousel/Carousel.tsx
  src/components/category/Badge/Badge.tsx
  src/components/layout/GNB/GNB.tsx
  src/components/rating/Rating.styles.ts
  src/pages/customer/request/components/search/components/DesignerListItem/index.styles.ts
  src/pages/customer/request/components/search/components/DesignerListItem/index.tsx
  src/pages/customer/request/components/search/index.tsx
  src/pages/designer/schedule/index.tsx
  src/pages/shop/components/ShopBadge/badge-modal/index.tsx
  src/pages/shop/components/ShopBadge/index.styles.ts
  src/pages/shop/components/ShopBadge/index.tsx
  src/pages/shop/components/ShopDetail/Career/index.tsx
  src/pages/shop/components/ShopDetail/ShopInfo/index.tsx
  src/pages/shop/components/ShopDetail/index.tsx
  src/pages/shop/components/ShopNav/index.tsx
  src/pages/shop/components/ShopOverview/OverviewInfo/index.tsx
  src/pages/shop/components/ShopOverview/ShopEvent/index.tsx
  src/pages/shop/components/ShopOverview/index.tsx
  src/pages/shop/components/ShopReview/ReviewItem/index.tsx
  src/pages/shop/index.tsx
  src/router/customer/request/index.tsx
  src/router/router.tsx
  src/types/customer/request/index.tsx
  src/types/designer/designer/index.ts
  src/utils/transformBadges.ts
Labels: 두명 이상 봐줘, 보면 좋아

#108 [PEAUTY-225] 미용사 견적 현황 Step3 api 연결
  public/svg/NoneComfirm.svg
  public/svg/NoneQuote.svg
  public/svg/NoneRequset.svg
  src/apis/customer/api.ts
  src/apis/customer/hooks/signUpCustomHook.tsx
  src/apis/customer/hooks/useUser.ts
  src/apis/customer/resources/auth/index.ts
  src/apis/designer/api.ts
  src/apis/designer/hooks/useUser.ts
  src/apis/designer/resources/designer-bidding-api/index.ts
  src/apis/designer/resources/designer/index.ts
  src/apis/external/kakaoMapAPI.ts
  src/assets/svg/NoneComfirm.tsx
  src/assets/svg/NoneQuote.tsx
  src/assets/svg/NoneRequset.tsx
  src/assets/svg/index.ts
  src/components/cards/Card/Card.stories.tsx
  src/components/cards/Card/Card.styles.ts
  src/components/cards/Card/Card.tsx
  src/components/modal/Modal/Modal.styles.ts
  src/components/modal/Modal/Modal.tsx
  src/components/petInfo/Info.styles.ts
  src/components/petInfo/Info.tsx
  src/components/profile-img/ProfileImg/ProfileImg.tsx
  src/components/stylist-Item/StylistItem.tsx
  src/components/toast/Toast.styles.ts
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/info/index.tsx
  src/pages/customer/pet/signup/components/Step/step2.tsx
  src/pages/customer/quote-detail/index.styles.ts
  src/pages/customer/request/components/choose-pet/index.tsx
  src/pages/customer/request/components/search/index.tsx
  src/pages/customer/request/index.tsx
  src/pages/customer/request/request-look/index.tsx
  src/pages/designer/quote/index.tsx
  src/pages/designer/quote/quote-form/index.styles.ts
  src/pages/designer/quote/quote-form/index.tsx
  src/pages/designer/quote/quoute-detail/index.styles.ts
  src/pages/designer/quote/quoute-detail/index.tsx
  src/pages/designer/status/components/not-found/index.styled.ts
  src/pages/designer/status/components/not-found/index.tsx
  src/pages/designer/status/index.tsx
  src/pages/designer/status/utils/index.tsx
  src/router/designer/quote/index.tsx
  src/router/designer/status/index.tsx
  src/style/color.ts
  src/types/customer/auth/index.ts
  src/types/customer/customer-bidding-api/index.ts
  src/types/designer/auth/index.ts
  src/types/designer/designer-bidding-api/index.ts
  src/types/designer/index.ts
  src/utils/dataformat.ts
Labels: 새로운 기능, 보면 좋아

#109 [PEAUTY-226] Shop 라이센스 이미지 연결
  src/apis/resources/designer/index.ts
  src/pages/shop/components/ShopBadge/index.tsx
  src/pages/shop/components/ShopDetail/License/index.styles.ts
  src/pages/shop/components/ShopDetail/License/index.tsx
  src/pages/shop/components/ShopDetail/index.tsx
  src/pages/shop/components/ShopOverview/OverviewInfo/index.tsx
  src/pages/shop/index.tsx
  src/types/customer/request/index.tsx
  src/types/designer/designer/index.ts
Labels: 새로운 기능

#110 Fix: 견적 요청시 이미 진행중인 강아지는 선택 불가능하도록 변경
  src/apis/customer/resources/bidding/index.ts
  src/apis/customer/resources/customer-bidding-api/index.ts
  src/components/cards/Card/Card.styles.ts
  src/components/cards/Card/Card.tsx
  src/pages/customer/request/components/choose-pet/index.tsx
  src/pages/customer/request/components/customize-grooming/index.tsx
  src/pages/customer/request/components/search/index.styles.ts
  src/pages/customer/request/components/search/index.tsx
  src/pages/customer/request/hooks/useEstimateProposalForm.tsx
  src/pages/customer/request/index.tsx
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/types/customer/bidding/index.ts
  src/types/customer/customer-bidding-api/index.ts
Labels: 보면 좋아

#113 [PEAUTY-227] Shop review 연결 및 이미지 갤러리 생성
  src/apis/customer/resources/review/index.ts
  src/components/bottom-sheet/BottomSheet.tsx
  src/components/button/CustomButton/CustomButton.styles.ts
  src/components/button/CustomButton/CustomButton.tsx
  src/components/star-rating/StarRating.tsx
  src/constants/routes.ts
  src/pages/customer/request/components/customize-grooming/index.styles.ts
  src/pages/customer/request/components/customize-grooming/index.tsx
  src/pages/customer/request/components/search/index.tsx
  src/pages/designer/quote/quote-form/index.tsx
  src/pages/shop/components/ShopOverview/index.tsx
  src/pages/shop/components/ShopReview/ImageGallery/index.styles.ts
  src/pages/shop/components/ShopReview/ImageGallery/index.tsx
  src/pages/shop/components/ShopReview/ReviewPhotos/index.styles.ts
  src/pages/shop/components/ShopReview/ReviewPhotos/index.tsx
  src/pages/shop/components/ShopReview/TotalImage/index.styles.ts
  src/pages/shop/components/ShopReview/TotalImage/index.tsx
  src/pages/shop/components/ShopReview/index.tsx
  src/pages/shop/index.tsx
  src/router/customer/index.tsx
  src/router/customer/request/index.tsx
  src/types/customer/bidding/index.ts
  src/types/customer/review/index.ts
  src/utils/dataformat.ts
Labels: 새로운 기능

#121 [Feature/status] 바뀐 타입 api 적용
  src/apis/customer/resources/bidding/index.ts
  src/pages/customer/status/index.tsx
  src/types/customer/bidding/index.ts
Labels: 버그픽스

#123 [PEAUTY-235] 반려견 등록 유효성 검사 추가 및 고객 요청 현황 반려견 없는 경우 설정
  public/svg/Dog1.svg
  public/svg/Dog2.svg
  src/assets/svg/Dog1.tsx
  src/assets/svg/Dog2.tsx
  src/assets/svg/index.ts
  src/components/toast/Toast.tsx
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/edit/index.styles.ts
  src/pages/customer/pet/edit/index.tsx
  src/pages/customer/pet/info/index.tsx
  src/pages/customer/pet/signup/components/Step/step1.tsx
  src/pages/customer/pet/signup/components/Step/step2.tsx
  src/pages/customer/pet/signup/index.styles.ts
  src/pages/customer/pet/signup/index.tsx
  src/pages/customer/status/components/DogProfile/index.tsx
  src/pages/customer/status/components/NotFoundPuppy/index.styles.ts
  src/pages/customer/status/components/NotFoundPuppy/index.tsx
  src/pages/customer/status/components/StatusTab/index.styles.ts
  src/pages/customer/status/index.tsx
  src/pages/designer/quote/quote-form/index.tsx
Labels: 보면 좋아

#125 [PEAUTY-250] 디테일 수정 2
  public/svg/female-icon.svg
  public/svg/male_icon.svg
  src/assets/svg/FemaleIcon.tsx
  src/assets/svg/MaleIcon.tsx
  src/assets/svg/index.ts
  src/components/button/DateDropBox/DateDropBox.tsx
  src/components/button/MultiSelectButton/MultiSelectButton.stories.tsx
  src/components/button/RadioSelectButton/RadioSelectButton.stories.tsx
  src/components/cards/Card/Card.styles.ts
  src/components/input/CustomInput/CustomInput.tsx
  src/components/profile-img/ProfileImg/ProfileImg.styles.ts
  src/pages/customer/mypage/detail/index.tsx
  src/pages/customer/mypage/edit/CustomerMyPageEdit.styles.ts
  src/pages/customer/mypage/edit/CustomerMyPageEdit.tsx
  src/pages/customer/mypage/index.tsx
  src/pages/customer/pet/edit/index.styles.ts
  src/pages/customer/pet/info/components/Gender.tsx
  src/pages/customer/pet/info/components/OptionButton.styles.ts
  src/pages/customer/pet/info/index.styles.ts
  src/pages/customer/request/components/customize-grooming/index.styles.ts
  src/pages/customer/request/components/customize-grooming/index.tsx
  src/pages/customer/request/components/search/components/DesignerListItem/index.styles.ts
  src/pages/customer/request/components/search/components/DesignerListItem/index.tsx
  src/pages/customer/request/components/search/index.tsx
  src/pages/designer/signup-detail/components/ShopInfoInputSection.tsx
  src/pages/designer/signup-detail/index.tsx
Labels: 보면 좋아

#127 [PEAUTY-236] 스케줄 api 연결
  src/apis/designer/resources/designer-bidding-api/index.ts
  src/components/button/InfoButton/InfoButton.styles.ts
  src/components/button/InfoButton/InfoButton.tsx
  src/components/petInfo/Info.styles.ts
  src/components/petInfo/Info.tsx
  src/components/profile-img/ProfileImg/ProfileImg.styles.ts
  src/pages/customer/quote-detail/index.styles.ts
  src/pages/customer/quote-detail/index.tsx
  src/pages/customer/request/components/customize-grooming/index.styles.ts
  src/pages/customer/review/history/components/ReviewableService.tsx
  src/pages/customer/status/components/CustomerInfo/index.styles.ts
  src/pages/customer/status/components/CustomerInfo/index.tsx
  src/pages/customer/status/index.tsx
  src/pages/designer/quote/quote-form/index.tsx
  src/pages/designer/quote/quoute-detail/index.tsx
  src/pages/designer/schedule/components/Dashboard.tsx
  src/pages/designer/schedule/index.styles.ts
  src/pages/designer/schedule/index.tsx
  src/pages/designer/status/index.tsx
  src/types/designer/designer-bidding-api/index.ts
Labels: 새로운 기능
